In [1]:
import requests
import pandas as pd
import time

In [2]:
def get_data(ticker, startTime):
    columns = [
                "OpenTime",
                "Open",
                "High",
                "Low",
                "Close",
                "TradeVolume",
                "CloseTime",
                "TradeValue",
                "TradeCount",
                "BuyVolume",
                "BuyValue",
                "Useless",
            ]
    df = pd.DataFrame(
        requests.get(
            "https://api.binance.com/api/v3/klines", 
            params={"symbol":ticker, "interval":"1d", "limit":1000, "startTime": int(startTime)}
        ).json(), columns=columns)
    
    for column in ["OpenTime", "CloseTime"]:
        df[column] = (
            pd.DatetimeIndex(pd.to_datetime(df[column], unit="ms"))
            .strftime("%Y%m%d%H%M%S")
            .astype(int)
        )
    df.index = pd.to_datetime(df["OpenTime"], format="%Y%m%d%H%M%S")
    df.index.name = "TimeStamp"
    return df

In [7]:
BTC= pd.concat([get_data("BTCUSDT", pd.Timestamp('20180101').value // 1e6), get_data("BTCUSDT", pd.Timestamp('20200926').value // 1e6)])
BTC

,OpenTime,Open,High,Low,Close,TradeVolume,CloseTime,TradeValue,TradeCount,BuyVolume,BuyValue,Useless
TimeStamp,,,,,,,,,,,,
2018-01-01,20180101000000,13715.65000000,13818.55000000,12750.00000000,13380.00000000,8609.91584400,20180101235959,114799747.44197057,105595,3961.93894600,52809747.44038045,0
2018-01-02,20180102000000,13382.16000000,15473.49000000,12890.02000000,14675.11000000,20078.09211100,20180102235959,279717107.43371920,177728,11346.32673900,158080088.68331682,0
2018-01-03,20180103000000,14690.00000000,15307.56000000,14150.00000000,14919.51000000,15905.66763900,20180103235959,236116868.33619011,162787,8994.95356600,133587333.24534808,0
2018-01-04,20180104000000,14919.51000000,15280.00000000,13918.04000000,15059.54000000,21329.64957400,20180104235959,312781583.79830782,170310,12680.81295100,186116793.01158931,0
2018-01-05,20180105000000,15059.56000000,17176.24000000,14600.00000000,16960.39000000,23251.49112500,20180105235959,369321956.48683753,192969,13346.62229300,211829900.67898224,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-04,20211104000000,62896.49000000,63086.31000000,60677.01000000,61395.01000000,35930.93314000,20211104235959,2218138026.70454070,1346081,17843.38035000,1101751566.38434540,0
2021-11-05,20211105000000,61395.01000000,62595.72000000,60721.00000000,60937.12000000,31604.48749000,20211105235959,1943346371.47038610,1243074,15769.15494000,969780612.68539310,0
2021-11-06,20211106000000,60940.18000000,61560.49000000,60050.00000000,61470.61000000,25590.57408000,20211106235959,1556774943.55372840,965309,12511.52761000,761294376.47169950,0
2021-11-07,20211107000000,61470.62000000,63286.35000000,61322.78000000,63273.59000000,25515.68830000,20211107235959,1585744720.19977190,1068629,13567.09782000,843384435.44095480,0
2021-11-08,20211108000000,63273.58000000,65639.08000000,63273.58000000,65056.05000000,14682.52403000,20211108235959,950052701.14109240,545879,7852.29313000,508148899.76593800,0

In [9]:
ETH= pd.concat([get_data("ETHUSDT", pd.Timestamp('20180101').value // 1e6), get_data("ETHUSDT", pd.Timestamp('20200926').value // 1e6)])
BTC

,OpenTime,Open,High,Low,Close,TradeVolume,CloseTime,TradeValue,TradeCount,BuyVolume,BuyValue,Useless
TimeStamp,,,,,,,,,,,,
2018-01-01,20180101000000,13715.65000000,13818.55000000,12750.00000000,13380.00000000,8609.91584400,20180101235959,114799747.44197057,105595,3961.93894600,52809747.44038045,0
2018-01-02,20180102000000,13382.16000000,15473.49000000,12890.02000000,14675.11000000,20078.09211100,20180102235959,279717107.43371920,177728,11346.32673900,158080088.68331682,0
2018-01-03,20180103000000,14690.00000000,15307.56000000,14150.00000000,14919.51000000,15905.66763900,20180103235959,236116868.33619011,162787,8994.95356600,133587333.24534808,0
2018-01-04,20180104000000,14919.51000000,15280.00000000,13918.04000000,15059.54000000,21329.64957400,20180104235959,312781583.79830782,170310,12680.81295100,186116793.01158931,0
2018-01-05,20180105000000,15059.56000000,17176.24000000,14600.00000000,16960.39000000,23251.49112500,20180105235959,369321956.48683753,192969,13346.62229300,211829900.67898224,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-04,20211104000000,62896.49000000,63086.31000000,60677.01000000,61395.01000000,35930.93314000,20211104235959,2218138026.70454070,1346081,17843.38035000,1101751566.38434540,0
2021-11-05,20211105000000,61395.01000000,62595.72000000,60721.00000000,60937.12000000,31604.48749000,20211105235959,1943346371.47038610,1243074,15769.15494000,969780612.68539310,0
2021-11-06,20211106000000,60940.18000000,61560.49000000,60050.00000000,61470.61000000,25590.57408000,20211106235959,1556774943.55372840,965309,12511.52761000,761294376.47169950,0
2021-11-07,20211107000000,61470.62000000,63286.35000000,61322.78000000,63273.59000000,25515.68830000,20211107235959,1585744720.19977190,1068629,13567.09782000,843384435.44095480,0
2021-11-08,20211108000000,63273.58000000,65639.08000000,63273.58000000,65056.05000000,14682.52403000,20211108235959,950052701.14109240,545879,7852.29313000,508148899.76593800,0

In [10]:
BTC

,OpenTime,Open,High,Low,Close,TradeVolume,CloseTime,TradeValue,TradeCount,BuyVolume,BuyValue,Useless
TimeStamp,,,,,,,,,,,,
2018-01-01,20180101000000,13715.65000000,13818.55000000,12750.00000000,13380.00000000,8609.91584400,20180101235959,114799747.44197057,105595,3961.93894600,52809747.44038045,0
2018-01-02,20180102000000,13382.16000000,15473.49000000,12890.02000000,14675.11000000,20078.09211100,20180102235959,279717107.43371920,177728,11346.32673900,158080088.68331682,0
2018-01-03,20180103000000,14690.00000000,15307.56000000,14150.00000000,14919.51000000,15905.66763900,20180103235959,236116868.33619011,162787,8994.95356600,133587333.24534808,0
2018-01-04,20180104000000,14919.51000000,15280.00000000,13918.04000000,15059.54000000,21329.64957400,20180104235959,312781583.79830782,170310,12680.81295100,186116793.01158931,0
2018-01-05,20180105000000,15059.56000000,17176.24000000,14600.00000000,16960.39000000,23251.49112500,20180105235959,369321956.48683753,192969,13346.62229300,211829900.67898224,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-04,20211104000000,62896.49000000,63086.31000000,60677.01000000,61395.01000000,35930.93314000,20211104235959,2218138026.70454070,1346081,17843.38035000,1101751566.38434540,0
2021-11-05,20211105000000,61395.01000000,62595.72000000,60721.00000000,60937.12000000,31604.48749000,20211105235959,1943346371.47038610,1243074,15769.15494000,969780612.68539310,0
2021-11-06,20211106000000,60940.18000000,61560.49000000,60050.00000000,61470.61000000,25590.57408000,20211106235959,1556774943.55372840,965309,12511.52761000,761294376.47169950,0
2021-11-07,20211107000000,61470.62000000,63286.35000000,61322.78000000,63273.59000000,25515.68830000,20211107235959,1585744720.19977190,1068629,13567.09782000,843384435.44095480,0
2021-11-08,20211108000000,63273.58000000,65639.08000000,63273.58000000,65056.05000000,14682.52403000,20211108235959,950052701.14109240,545879,7852.29313000,508148899.76593800,0

In [11]:
BTC.reset_index()[["TimeStamp", "Close", "TradeVolume", "TradeCount"]].to_csv("Data/BTCUSDT.csv")

In [12]:
ETH.reset_index()[["TimeStamp", "Close", "TradeVolume", "TradeCount"]].to_csv("Data/ETHUSDT.csv")