In [158]:
import pandas as pd
import altair as alt

In [159]:
df_eth = pd.read_csv(
    "Data/BTCUSDT.csv", index_col="TimeStamp"
).drop(["Unnamed: 0"], axis=1).rename(columns={
    "Close":"CloseETH",
    "TradeVolume":"TradeVolumeETH",
    "TradeCount":"TradeCountETH"
})
df_eth.index = pd.to_datetime(df_eth.index)
df_eth.sample(3)

            CloseETH  TradeVolumeETH  TradeCountETH
TimeStamp
2020-05-12   8810.79    86522.780066         784859
2020-11-24  19160.01   113581.509241        2179862
2018-05-25   7457.00    26739.956640         239025

In [160]:
df_btc = pd.read_csv(
    "Data/BTCUSDT.csv", index_col="TimeStamp"
).drop(["Unnamed: 0"], axis=1)
df_btc.index = pd.to_datetime(df_btc.index)
df_btc.sample(3)

              Close   TradeVolume  TradeCount
TimeStamp
2018-09-28  6634.58  42399.448523      211849
2019-05-15  8169.87  37884.327211      347533
2018-02-10  8533.98  49381.512653      537578

In [157]:
ret = df_btc.merge(df_eth, left_index=True, right_index=True)
for field in ["Difficulty", "TransactionFee", "Transactions", "UniqueAddress", "MinerRevenue", "TotalMarketValue", "TotalHashRate"]:
    df = pd.read_csv("Data/{}.csv".format(field)).set_index(["TimeStamp"])
    df.index = pd.to_datetime(pd.to_datetime(df.index, format="%Y-%m-%d %H:%M:%S").date)
    df = df.groupby(df.index).mean()
    ret = ret.merge(df, left_index=True, right_index=True)
    print(ret.shape)
ret

(1098, 7)
(1098, 8)
(1098, 9)
(1095, 10)
(1095, 11)
(1092, 12)
(1091, 13)

,Close,TradeVolume,TradeCount,CloseETH,TradeVolumeETH,TradeCountETH,Difficulty,TransactionFee,Transactions,UniqueAddress,MinerRevenue,TotalMarketValue,HashRate
2018-11-10,6433.05,7714.829926,97746,6433.05,7714.829926,97746,7.184405e+12,42.437533,252499.0,448643.0,1.083647e+07,1.106154e+11,4.765251e+07
2018-11-11,6449.81,8213.507117,98435,6449.81,8213.507117,98435,7.184405e+12,47.211209,246991.0,422963.0,1.166074e+07,1.102939e+11,4.612191e+07
2018-11-12,6453.07,10132.782567,123144,6453.07,10132.782567,123144,7.184405e+12,37.422853,300006.0,510342.0,1.140461e+07,1.101502e+11,4.724435e+07
2018-11-13,6457.66,11790.564933,150940,6457.66,11790.564933,150940,7.184405e+12,34.235608,279160.0,491741.0,9.557212e+06,1.090161e+11,4.709129e+07
2018-11-14,5922.41,46478.964003,319011,5922.41,46478.964003,319011,7.184405e+12,35.221224,292755.0,524970.0,1.048610e+07,1.076257e+11,4.668313e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-03,62896.48,43336.090490,1601925,62896.48,43336.090490,1601925,2.165934e+13,222.482698,288746.0,724143.0,6.424099e+07,1.188620e+12,1.577950e+08
2021-11-04,61395.01,35930.933140,1346081,61395.01,35930.933140,1346081,2.165934e+13,194.638054,289141.0,729141.0,5.627784e+07,1.168513e+12,1.601683e+08
2021-11-05,60937.12,31604.487490,1243074,60937.12,31604.487490,1243074,2.165934e+13,212.102012,285946.0,721315.0,6.064972e+07,1.156884e+12,1.603435e+08
2021-11-06,61470.61,25590.574080,965309,61470.61,25590.574080,965309,2.165934e+13,251.358805,236233.0,623103.0,5.937924e+07,1.153441e+12,1.597974e+08
2021-11-07,63273.59,25515.688300,1068629,63273.59,25515.688300,1068629,2.165934e+13,265.469336,226128.0,591980.0,6.003005e+07,1.168589e+12,1.613793e+08

In [162]:
ret.to_csv("Data/Data.csv", index_label="TimeStamp")

In [163]:
ret.sample(3)

,Close,TradeVolume,TradeCount,CloseETH,TradeVolumeETH,TradeCountETH,Difficulty,TransactionFee,Transactions,UniqueAddress,MinerRevenue,TotalMarketValue,HashRate
2021-04-09,58142.54,40831.884911,1615962,58142.54,40831.884911,1615962,2.313744e+13,191.393851,324720.0,853581.0,6.293681e+07,1.090677e+12,1.655520e+08
2021-10-26,60328.81,40217.500830,1334460,60328.81,40217.500830,1334460,2.008246e+13,201.898870,294029.0,715943.0,5.936412e+07,1.179971e+12,1.554503e+08
2021-06-11,37331.98,78466.005300,1727645,37331.98,78466.005300,1727645,2.104773e+13,118.954072,216502.0,616007.0,2.575379e+07,6.867017e+11,1.402026e+08

In [165]:
(ret["Difficulty"] / ret["HashRate"]).describe()

count      1091.000000
mean     139704.698557
std       11484.710322
min      115707.455449
25%      133621.498176
50%      138190.356508
75%      142212.326342
max      227489.456029
dtype: float64